### ISSUE TITLE
axlsx (LoadError)

### ISSUE THREAD

**Issue by dtur0** [barbolo/ir_investidor#17]
Ocorre um erro ao executar script de converter notas da Clear:

```
u@desktop MINGW64 ~/Downloads/ir_investidor-master
$ docker-compose run web bundle exec ruby scripts/clear.rb  pdf
Starting ir_investidor-master_db_1 ... done
Starting ir_investidor-master_redis_1 ... done
Traceback (most recent call last):
        1: from scripts/clear.rb:9:in `<main>'
scripts/clear.rb:9:in `require': cannot load such file -- axlsx (LoadError)
```

OBS: Estou usando Windows 7 e o Docker Toobox.

Resolvi o erro executando os comandos:

```
docker-compose run web bundle add  axlsx
docker-compose run web bundle add  zip-zip
```

**Comment by dtur0** [comment]
Outro erro que ocorre depois de conseguir gerar o arquivo de xlsx e tentar carregar:

```
Descrição do erro:
Cabeçalhos não encontrados: CUSTOS, IRRF, NOVO PAPEL, QTD ANTIGA, QTD NOVA, COMUNS A COMPENSAR, DAYTRADE A COMPENSAR, FIIS A COMPENSAR, IRRF A COMPENSAR
```

Se adicionar esses campos na mão e preencher com zeros as seguintes colunas:

CORRETAGEM | ISS (5%) | TAXAS B3 | CUSTOS | IRRF

E preencher com PRECO*QTD a coluna VALOR, então ele consegue carregar a planilha.
